### ISSUE TITLE
Add semantic pull request title ci

### ISSUE THREAD

**Issue by benswinburne** [guyfedwards/emojo#13]
https://github.com/probot/semantic-pull-requests

@guyfedwards you need to do this because you own the repo; it won't let me.

Prevents PR titles polluting the nice standardised commit history when merging/squashing etc

**Comment by guyfedwards** [comment]
Would this not be better solved by rebase or squash merging

**Comment by benswinburne** [comment]
Nah squashing and rebasing creates a merge commit with whatever message you
like. Look at the log from some of the squashed merges we have done which
have random names

This ci checks the name of the merge commit and blocks merge squash or
rebase merge until you fix the name

**Comment by guyfedwards** [comment]
Hmm you shouldn't have a merge commit with squash/rebase just the commit you create/choose. I guess I'm wondering how this can help in those situations as its only linting the PR name and not the custom name set when squashing

**Comment by benswinburne** [comment]
squashing creates a commit, and you can type or choose the message from the existing commits etc. this prevents you merging prs and creating commit messages which break the rules.

![image](https://user-images.githubusercontent.com/1208977/48318180-7bebb700-e5ca-11e8-8347-f96c88c3d9da.png)
☝️ bad commit message cause by pr

**Comment by guyfedwards** [comment]
~Isn't this just a bot linting the PR titles? My point is that if you still squash and merge or rebase and merge there is nothing stopp~ ohhhh, I mean you could still then change the commit to be incorrect but that would be ultimate :trollface:

**Comment by benswinburne** [comment]
When you create a PR, if you name it "Cheesecakes are cool" then that's the name of the squashed commit unless you change it when you press the squash and merge button. This prevents you merging unless that commit you're creating follows the rules set out by conventional commits (you'd need to tick the box on the repo settings stopping merges before CI passes too obviously)

**Comment by benswinburne** [comment]
What's the craic with this? @guyfedwards

**Comment by guyfedwards** [comment]
Need to create a PR to test, should just work™

**Comment by benswinburne** [comment]
What about the "shit title" and "extra shit title" ?

**Comment by benswinburne** [comment]
@guyfedwards 	this is working now, right?

**Comment by guyfedwards** [comment]
Should be. I haven't tested it but the change was merged upstream.
